Mil 67 api calls
402-Code/medical-calculator pull request #12
Opened 2022-01-29 23:41 UTC by szymonkwak

2022-01-31 23:02 UTC, matizaj commented
when use 'await' wrap it in try catch block. Try to rewrite then catch block using async await keywords

2022-01-31 23:02 UTC, matizaj requested changes
small changes. good work :)

2022-02-21 21:37 UTC, CaptainObjective commented on frontend/src/utils/getRequest.js
> +const sendGetRequest = (body) => {
I would suggest to create new folder "api" to store code related to api requests

2022-02-22 01:06 UTC, CaptainObjective commented on frontend/src/utils/getRequest.js
> +const sendGetRequest = (body) => {
Also I would suggest to rename function to sth more verbose, e.x: getMedicationsList

2022-03-02 21:10 UTC, closed without merging