Mil 108 post diseases
402-Code/medical-calculator pull request #44
Opened 2022-03-01 21:55 UTC by szymonkwak

2022-03-02 17:50 UTC, CaptainObjective requested changes

2022-03-02 19:01 UTC, szymonkwak commented on server/src/routes/disease/index.js
> +diseaseRouter.use('/', postDisease);
I can't believe what I wrote, but I did it

2022-03-02 19:02 UTC, szymonkwak commented on server/src/routes/disease/postDisease.js
> +  const disease = { eventLog: [], initialDrug: req.body.initialDrug };
Changed

2022-03-02 19:18 UTC, CaptainObjective commented on server/src/routes/disease/postDisease.js
> +  const disease = { eventLog: [req.body.event], initialDrug: req.body.initialDrug };
I am afride we need to create can't rely on on frontend to pass it :)

2022-03-03 17:09 UTC, CaptainObjective approved these changes

2022-03-03 21:41 UTC, merged